export const APP_TEST_ACTION = 'APP_TEST_ACTION';
export const APP_TEST_ACTION_DVA = 'APP_TEST_ACTION_DVA';

//CHECKOUT/CART
export const CART_ADD = 'CART_ADD';
export const CART_REMOVE = 'CART_REMOVE';

//NAV
export const NAV_NAVIGATE = 'Navigation/NAVIGATE';
export const NAV_BACK = 'Navigation/BACK';

//WEBVIEWS
export const WEBVIEW_CHEKOUT_MESSAGE_IN='WEBVIEW_CHEKOUT_MESSAGE_IN';
export const WEBVIEW_CHEKOUT_MESSAGE_OUT='WEBVIEW_CHEKOUT_MESSAGE_OUT';
export const WEBVIEW_CHEKOUT_CLEAN_QUE='WEBVIEW_CHEKOUT_CLEAN_QUE';
export const RECEIVED_USER_CARD_NONCE='RECEIVED_USER_CARD_NONCE';

//PAYMENTS
export const PERSIST_PAYMENT_METHOD='PERSIST_PAYMENT_METHOD';
export const PAYMENT_CREATE_NEW='PAYMENT_CREATE_NEW';
export const PAYMENT_BY_CARD='PAYMENT_BY_CARD';
export const PAYMENT_BY_NONCE='PAYMENT_BY_NONCE';
export const PAYMENT_PENDING='PAYMENT_PENDING';
export const PAYMENT_SUCCESS='PAYMENT_SUCCESS';
export const PAYMENT_FAILED='PAYMENT_FAILED';
export const PAYMENT_UPDATE='PAYMENT_UPDATE';
export const RESET_PAYMENT_INSTRUMENT='RESET_PAYMENT_INSTRUMENT';

//NOTIFICATIONS
export const PUSH_NOTIFY='PUSH_NOTIFY';
export const SHOW_NOTIFY='SHOW_NOTIFY';
export const HIDE_NOTIFY='HIDE_NOTIFY';

//ORDERS
export const PLACE_ORDER='PLACE_ORDER';

//SHOPS
export const SHOPS_ADDED='SHOPS_ADDED';
export const SHOP_SELECTED='SHOP_SELECTED';

//CHECKOUT
export const SHOW_CHECKOUT_FORM='SHOW_CHECKOUT_FORM';
export const HIDE_CHECKOUT_FORM='HIDE_CHECKOUT_FORM';

//SYNC
export const LOADING_ACTIVE='LOADING_ACTIVE';
export const LOADING_NOT_ACTIVE='LOADING_NOT_ACTIVE';
export const FETCHING_ACTIVE='FETCHING_ACTIVE';
export const FETCHING_NOT_ACTIVE='FETCHING_NOT_ACTIVE';

export const NONE = null;