export const ADDING_CARD='ADDING_CARD';
export const REMOVING_CARD='REMOVING_CARD';

export const USER_CARD_NEW='USER_CARD_ADD';
export const USER_CARD_SAVE='USER_CARD_SAVE';
export const USER_CARD_SELECT='USER_CARD_SELECT';
export const USER_CARD_REMOVE='USER_CARD_REMOVE';

export const USER_NONCE_SAVE='USER_NONCE_SAVE';
export const USER_NONCE_FORM='USER_NONCE_FORM';
export const USER_NONCE_FORM_CLOSE='USER_NONCE_FORM_CLOSE';

export const SETTING_ONE_TIME_PAYMENT='SETTING_ONE_TIME_PAYMENT';
export const MAKING_ORDER='MAKING_ORDER';

export const EDITING_ACCOUNT='EDITING_ACCOUNT';

export const DROP_CART='DROP_CART';

export const LOGIN_IN='LOGIN_IN';
export const LOGIN_OUT='LOGIN_OUT';
